### ISSUE TITLE
Vanadium server

### ISSUE THREAD

**Issue by joeblew99** [asimshankar/triangles#1]
With the current code I need to use Google's vanadium servers I believe.

I was wondering seeing if I can run this on a LAN without the need to communicate with their servers.

I am wondering about using sync base locally as a way to do this.

I am raising this as a discussion about extending your current example. Curious what you think.

I have only starts learning vanadium however, but it looks very promising.

Thanks in advance ...

**Comment by asimshankar** [comment]
I don't believe this depends on any Google run servers.

It's using the discovery API which uses mDNS on the local network to find services and no communication with external services is required.

Hope that helps. Closing this out, but feel free to re-open if you have follow up concerns or if I'm mistaken :)
